planning_index:
    path:   /
    defaults:  { _controller: PlanningBundle:Planning:index }

# establishments routes

planning_establishments:
    path:   /etablissements
    defaults:  { _controller: PlanningBundle:Establishments:index }

planning_edit_establishment:
    path:   /etablissements/{id}/edit
    defaults:  { _controller: PlanningBundle:Establishments:edit }
    requirements:
        id: \d+

planning_delete_establishment:
    path:   /etablissements/{id}/delete
    defaults:  { _controller: PlanningBundle:Establishments:delete }
    requirements:
        id: \d+

# courses routes

planning_courses:
    path:   /cours
    defaults:  { _controller: PlanningBundle:Courses:index }

planning_edit_course:
    path:   /cours/{id}/edit
    defaults:  { _controller: PlanningBundle:Courses:edit }
    requirements:
        id: \d+

planning_delete_course:
    path:   /cours/{id}/delete
    defaults:  { _controller: PlanningBundle:Courses:delete }
    requirements:
        id: \d+

#classrooms routes

classrooms:
    path:   /salles
    defaults:  { _controller: PlanningBundle:Classrooms:index }

classroom_edit:
    path:   /salle/{id}/edit
    defaults:  { _controller: PlanningBundle:Classrooms:edit }
    requirements:
        id: \d+

classroom_delete:
    path:   /salle/{id}/delete
    defaults:  { _controller: PlanningBundle:Classrooms:delete }
    requirements:
        id: \d+