# blog:
#   path:   /blog/{page}
#   defaults:  { _controller: AcmeBlogBundle:Blog:index, page: 1 }
#   requirements:
#     page:  \d+


planning_index:
  path:   /
  defaults:  { _controller: PlanningBundle:Planning:index }

planning_establishments:
  path:   /etablissements
  defaults:  { _controller: PlanningBundle:Planning:establishments }

